disp('Functions to optimize:');
disp('1-25. CEC05 benchmark functions (D=10 or 30)');
disp('26. Sphere');
disp('27. Rastrigin');
disp('28. Six Hump Camel back (D = 2)');
disp('29. Step');
disp('30. Rosenbrock');
disp('31. Ackley');
disp('32. Griewank');
disp('33. Salomon');
disp('34. Normalized Schwefel');
disp('35. Quartic function, i.e. noise');
disp('36. Rotated hyper-ellipsoid');
disp('37. Norwegian function');
disp('38. Alpine');
disp('39. Branin (D = 2)');
disp('40. Easom (D = 2)');
disp('41. Goldstein and Price (D = 2)');
disp('42. Shubert (D = 2)');
disp('43. Hartmann(3,4) (D = 3)');
disp('44. Shekel (D = 4)');
disp('45. Levy');
disp('46. Michalewicz (D = 10)');
disp('47. Shifted Griewank (D = 10 or D = 30)');
disp('48. Gear Train (D = 4)');
disp('49. Pressure Vessel (D = 4)');
disp('50. Tripod (D = 2)');
disp('51. Compression Spring (D=3)');